default:
  db:
    drv: !expr RSQLite::SQLite()
    dbname: "../portfolio.db"
evaluations:
  db:
    drv: !expr RSQLite::SQLite()
    dbname: "/data/portfolio.db"
rsconnect:
  db:
    drv: !expr odbc::odbc()
    dsn: "SQL Server (Finance)"
